### ISSUE TITLE
Bug - TVariables should no be set to an empty object ({}) when variables are not set

### ISSUE THREAD

**Issue by Newbie012** [MedFlyt/eslint-plugin-graphql-type-checker#1]
Given the following code:

```ts
Apollo.useQuery(gql`
    query {
        patient(id: 10) {
            firstName
        }
    }
`);
```

The plugin will add the following annotations:

```
Apollo.useQuery<{ patient: { firstName: string } }, {}>(gql`
  ...
`);
```

Which causes the following lint to fail:

```
Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.eslint@typescript-eslint/ban-types
```

It should change fix it to:

```
Apollo.useQuery<{ patient: { firstName: string } }>(gql`
  ...
`);
```

**Comment by Oblosys** [comment]
Good point, empty object types are always a bit of a nuisance. Just leaving out the second type parameter might not be the best solution though. It would require that for every operation annotated by the plugin the second type parameter is optional, which may be a bit of a strong restriction, as the plugin is not just used for Apollo. And also, the default for the second type parameter of `useQuery` is `Record<string, any>`, so leaving it out will throw almost all type checking out of the window (though it's still better than `{}`).

I think using `Record<PropertyKey, never>` may be the best option here.

**Comment by Newbie012** [comment]
fixed in https://github.com/MedFlyt/eslint-plugin-graphql-type-checker/pull/3
